config/routes.rb
Rails.application.routes.draw do
  namespace :legacy do
    resources :todos
  end

  resources :todos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/legacy.rb
module Legacy
  def self.table_name_prefix
    'legacy_'
  end
end

app/models/legacy/record.rb
module Legacy
  class Record < ActiveRecord::Base
    self.abstract_class = true
  
    connects_to database: { writing: :legacy, reading: :legacy }
  end
end

app/models/legacy/todo.rb
class Legacy::Todo < Legacy::Record
  validates :name, presence: true
  validates :detail, presence: true
end

app/models/primary_record.rb
class PrimaryRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: { writing: :primary, reading: :primary }
end

app/models/todo.rb
class Todo < PrimaryRecord
  validates :name, presence: true
  validates :detail, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/legacy/todos_controller.rb
class Legacy::TodosController < ApplicationController
  before_action :set_legacy_todo, only: %i[ show edit update destroy ]

  # GET /legacy/todos or /legacy/todos.json
  def index
    @legacy_todos = Legacy::Todo.all
  end

  # GET /legacy/todos/1 or /legacy/todos/1.json
  def show
  end

  # GET /legacy/todos/new
  def new
    @legacy_todo = Legacy::Todo.new
  end

  # GET /legacy/todos/1/edit
  def edit
  end

  # POST /legacy/todos or /legacy/todos.json
  def create
    @legacy_todo = Legacy::Todo.new(legacy_todo_params)

    respond_to do |format|
      if @legacy_todo.save
        format.html { redirect_to @legacy_todo, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @legacy_todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @legacy_todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legacy/todos/1 or /legacy/todos/1.json
  def update
    respond_to do |format|
      if @legacy_todo.update(legacy_todo_params)
        format.html { redirect_to @legacy_todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @legacy_todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @legacy_todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legacy/todos/1 or /legacy/todos/1.json
  def destroy
    @legacy_todo.destroy
    respond_to do |format|
      format.html { redirect_to legacy_todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legacy_todo
      @legacy_todo = Legacy::Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def legacy_todo_params
      params.require(:legacy_todo).permit(:name, :detail, :is_done)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :detail, :is_done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/legacy/todos_helper.rb
module Legacy::TodosHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMultiDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/legacy/todos/_form.html.erb
<%= form_with(model: legacy_todo) do |form| %>
  <% if legacy_todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(legacy_todo.errors.count, "error") %> prohibited this legacy_todo from being saved:</h2>

      <ul>
        <% legacy_todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>

  <div class="field">
    <%= form.label :is_done %>
    <%= form.check_box :is_done %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/legacy/todos/edit.html.erb
<h1>Editing Legacy Todo</h1>

<%= render 'form', legacy_todo: @legacy_todo %>

<%= link_to 'Show', @legacy_todo %> |
<%= link_to 'Back', legacy_todos_path %>

app/views/legacy/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Legacy Todos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Detail</th>
      <th>Is done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @legacy_todos.each do |legacy_todo| %>
      <tr>
        <td><%= legacy_todo.name %></td>
        <td><%= legacy_todo.detail %></td>
        <td><%= legacy_todo.is_done %></td>
        <td><%= link_to 'Show', legacy_todo %></td>
        <td><%= link_to 'Edit', edit_legacy_todo_path(legacy_todo) %></td>
        <td><%= link_to 'Destroy', legacy_todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Legacy Todo', new_legacy_todo_path %>

app/views/legacy/todos/new.html.erb
<h1>New Legacy Todo</h1>

<%= render 'form', legacy_todo: @legacy_todo %>

<%= link_to 'Back', legacy_todos_path %>

app/views/legacy/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @legacy_todo.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @legacy_todo.detail %>
</p>

<p>
  <strong>Is done:</strong>
  <%= @legacy_todo.is_done %>
</p>

<%= link_to 'Edit', edit_legacy_todo_path(@legacy_todo) %> |
<%= link_to 'Back', legacy_todos_path %>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>

  <div class="field">
    <%= form.label :is_done %>
    <%= form.check_box :is_done %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Detail</th>
      <th>Is done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= todo.detail %></td>
        <td><%= todo.is_done %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @todo.detail %>
</p>

<p>
  <strong>Is done:</strong>
  <%= @todo.is_done %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>